### ISSUE TITLE
Spelling error of methong moveRelativeToPosision, should it have been moveRelativeToPosition

### ISSUE THREAD

**Issue by RobSteele49** [rpineau/MFDeluxe#1]
On line 262 of the MFDeluxe.cpp code you have:

int CMFDeluxeController::moveRelativeToPosision(int nSteps)
{

On line 72 of MFDeluxe.h you have

    int         moveRelativeToPosision(int nSteps);

In both cases it appears the word should have been 'position' and the method name should have been moveRelativeToPosition.

(You can e-mail me at robsteele49@yahoo.com as I use both the gmail and yahoo accounts with the same name.

**Comment by rpineau** [comment]
Hi Rob,
yea, that's a typo (but doesn't impact the code).



> On Jan 12, 2024, at 09:35, Rob Steele (gmail) ***@***.***> wrote:
> 
> 
> On line 262 of the MFDeluxe.cpp code you have:
> int CMFDeluxeController::moveRelativeToPosision(int nSteps)
> {
> On line 72 of MFDeluxe.h you have
> int moveRelativeToPosision(int nSteps);
> 
> In both cases it appears the word should have been 'position' and the method name should have been moveRelativeToPosition.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/rpineau/MFDeluxe/issues/1", "url": "https://github.com/rpineau/MFDeluxe/issues/1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]


--

|        Rodolphe Pineau    RTI-Zone        |
|         http://www.rti-zone.org/                 |

**Comment by rpineau** [comment]
fixed,
