### ISSUE TITLE
My misunderstanding of how to compile this software

### ISSUE THREAD

**Issue by RobSteele49** [rpineau/MFDeluxe#2]
I'm wanting to use this code for controlling my JMI MotoFocus Deluxe focuser and the code looks like exactly what I need. But, I'm not sure of the directory structure and which repositories I need to check out to make this work for me. Is there a document that describes this?

The error I'm getting when I do a 'make all' is:

astroberry@astroberry:~/git/MFDeluxe $ make all
g++  -fPIC -Wall -Wextra -O2 -g -DSB_LINUX_BUILD -I. -I./../../  -c -o main.o main.cpp
In file included from main.cpp:1:
main.h:7:10: fatal error: ../../licensedinterfaces/basicstringinterface.h: No such file or directory
 #include "../../licensedinterfaces/basicstringinterface.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: main.o] Error 1

Which indicates I'm missing the respository basicstringinterface.h. But, I'm not sure which of your repositories this lives in.

Any help on this would be appreciated.

**Comment by rpineau** [comment]
This code is for a X2 plugin for TheSkyX so it needs the SDK from software bisque X2 Examples.
This is not a standalone application.
If you just  want to build a standalone application you probably can use the MFDeluxe.{cpp,h} code and create a CMFDeluxeController object after removing all the reference to the Software Bisque X2 SDK and replacing the missing macro as well as the whole serial port access code (SerXInterface is a class from the X2 SDK so you would need to re-implement this).
IF you are only trying to use this with TheSkyX then you need to checkout this repo inside the X2 examples  in x2/focuserplugins

**Comment by RobSteele49** [comment]
My actual target is to have an indi device driver for the JMI Motofocus
Deluxe focuser. Your code looks like an excellent starting point. I
appreciate the starting point for my coding effort.

Rob

**Comment by rpineau** [comment]
So yes, you should mostly focus (pun intended ;) ) no the code in MFDeluxe.{cpp,h}
You can remove the specific X2 stuff and use the INDI tty_write , tty_write_string, tty_nread_section function instead of the m_pSerx->open, m_pSerx->writeFile ... 
You can replace the ERR_xxxx code with your own (there are from the X2 plugin )
Replace all call to  m_pSleeper->sleep with std::this_thread::sleep_for(std::chrono::milliseconds(value));
That should get you close to what you need.
